CFLAGS=-g -O2 -Wall -DWIN32
LDFLAGS=-g -O2 -Wall 
LDLIBS=-lmingw32 -lSDL2main -lSDL2 -lSDL2_net

PROGRAMS=$(basename $(wildcard *.c))

all: $(PROGRAMS)

clean:
	rm -f $(PROGRAMS) *.o

new: clean all

tcpmulticlient.o: tcputil.h
tcpmultiserver.o: tcputil.h

tcptimesyncclient.o: tcptimesync.h
tcptimesyncserver.o: tcptimesync.h
