GCC=g++

CPPFLAGS=-std=c++11 -Werror -Wall -Wextra -Wpedantic -Weffc++ \
	-Woverloaded-virtual -Wctor-dtor-privacy -Wnon-virtual-dtor \
	-Wconversion -Wsign-conversion -Winit-self -Wunreachable-code

# TODO: add
#	-Wold-style-cast 

LDLIBS=-lpthread

all: threads_tst

