#
# mingw32-make
#

CPPFLAGS=--std=c++17 -Werror -Wall -Wextra -Wpedantic -Weffc++ -Woverloaded-virtual -Wctor-dtor-privacy -Wnon-virtual-dtor -Wold-style-cast -Wconversion -Wsign-conversion -Winit-self -Wunreachable-code
LDLIBS=-lpthread

all: getwch

getwch: ms-win-only

.PHONY: all getwch
